### ISSUE TITLE
Hehehe

### ISSUE THREAD

**Issue by 0x1234aAzffa** [VenixPLL/LightProxynetty#5]

**Comment by iNyatix** [comment]
🤔

**Comment by 0x1234aAzffa** [comment]
> 🤔

I can use beta lightproxy 2.0?

**Comment by iNyatix** [comment]
no, we're not searching beta testers

**Comment by 0x1234aAzffa** [comment]
> no, we're not searching beta testers

When it release?

**Comment by iNyatix** [comment]
i don't know, we will see..

**Comment by 0x1234aAzffa** [comment]
> i don't know, we will see..

.-.

**Comment by iNyatix** [comment]
^^
